---
- name: Get the Kubernetes project id
  action: uri
      method=GET
      status_code=200
      url="http://{{ rancher_server }}:{{ rancher_port }}/v1/projects" return_content=yes
  register: kube_project_id

- name: Return the registration token URL of Rancher server
  action: uri
      method=POST
      status_code=201
      url="http://{{ rancher_server }}:{{ rancher_port }}/v1/registrationtokens?projectId={{ kube_project_id.json['data'][1]['id'] }}" return_content=yes
  register: rancher_token_url

- name: Return the registration URL of Rancher server
  action: uri
      method=GET
      url={{ rancher_token_url.json['links']['self'] }} return_content=yes
  register: rancher_token

- name: Check if the rancher-agent is running
  command: docker ps -a
  register: containers

- name: Register the Host machine with the Rancher server
  docker_container:
      name: "{{ rancher_agent_name }}"
      image: "{{ rancher_token.json['image'] }}"
      privileged: yes
      detach: True
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /var/lib/rancher:/var/lib/rancher
      command: "{{ rancher_token.json['registrationUrl'] }}"
      state: started
      env:
        CATTLE_HOST_LABELS='compute=true'
  when: "{{ rancher_agent_name not in containers.stdout }}"
